export const userData = [
    {
        name: 'Jan',
        "Active Users": 4000,
    },
    {
        name: 'Feb',
        "Active Users": 3000,
    },
    {
        name: 'Mar',
        "Active Users": 2000,
    },
    {
        name: 'Apr',
        "Active Users": 2780,
    },
    {
        name: 'May',
        "Active Users": 1890,
    },
    {
        name: 'Jun',
        "Active Users": 2390,
    },
    {
        name: 'Jul',
        "Active Users": 3490,
    },
    {
        name: 'Aug',
        "Active Users": 5820,
    },
    {
        name: 'Sep',
        "Active Users": 2190,
    },
    {
        name: 'Oct',
        "Active Users": 1034,
    },
    {
        name: 'Nov',
        "Active Users": 4903,
    },
    {
        name: 'Dec',
        "Active Users": 3211,
    },
]

export const productData = [
    {
        name: 'Jan',
        "Sales": 4000,
    },
    {
        name: 'Feb',
        "Sales": 3000,
    },
    {
        name: 'Mar',
        "Sales": 3650,
    },
]

export const userList = [
    { 
        id: 1, 
        username: 'Jon Snow', 
        avatar: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        email: "Hon@gmail.com",
        status: "active",
        transactions: "32 450 XAF",
    },
    { 
        id: 2, 
        username: 'Peter Pan', 
        avatar: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        email: "PanPeter@gmail.com",
        status: "active",
        transactions: "32 450 XAF",
    },
    { 
        id: 3, 
        username: 'John Doe', 
        avatar: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        email: "jd@gmail.com",
        status: "active",
        transactions: "32 450 XAF",
    },
    { 
        id: 4, 
        username: 'Suzzy Layer', 
        avatar: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        email: "Layer@gmail.com",
        status: "active",
        transactions: "32 450 XAF",
    },
    { 
        id: 5, 
        username: 'Dalila Kenge', 
        avatar: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        email: "KengeDa@gmail.com",
        status: "active",
        transactions: "32 450 XAF",
    },
    { 
        id: 6, 
        username: 'Cianie Mayors', 
        avatar: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        email: "Mayors@gmail.com",
        status: "active",
        transactions: "32 450 XAF",
    },
    { 
        id: 7, 
        username: 'Jon Snow', 
        avatar: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        email: "Hon@gmail.com",
        status: "active",
        transactions: "32 450 XAF",
    },
    { 
        id: 8, 
        username: 'Peter Pan', 
        avatar: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        email: "PanPeter@gmail.com",
        status: "active",
        transactions: "32 450 XAF",
    },
    { 
        id: 9, 
        username: 'John Doe', 
        avatar: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        email: "jd@gmail.com",
        status: "active",
        transactions: "32 450 XAF",
    },
    { 
        id: 10, 
        username: 'Suzzy Layer', 
        avatar: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        email: "Layer@gmail.com",
        status: "active",
        transactions: "32 450 XAF",
    },
    { 
        id: 11, 
        username: 'Dalila Kenge', 
        avatar: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        email: "KengeDa@gmail.com",
        status: "active",
        transactions: "32 450 XAF",
    },
    { 
        id: 12, 
        username: 'Cianie Mayors', 
        avatar: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        email: "Mayors@gmail.com",
        status: "active",
        transactions: "32 450 XAF",
    },
];

export const productList = [
    { 
        id: 1, 
        name: 'Apples fruit',
        img: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        stock: 123,
        status: "active",
        price: "32 450 XAF",
    },
    { 
        id: 2, 
        name: 'Banana fruit', 
        img: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        stock: 123,
        status: "active",
        price: "32 450 XAF",
    },
    { 
        id: 3, 
        name: 'Tomoto fruit', 
        img: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        stock: 123,
        status: "active",
        price: "32 450 XAF",
    },
    { 
        id: 4, 
        name: 'Macbook', 
        img: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        stock: 123,
        status: "active",
        price: "32 450 XAF",
    },
    { 
        id: 5, 
        name: 'DELL XPS', 
        img: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        stock: 123,
        status: "active",
        price: "32 450 XAF",
    },
    { 
        id: 6, 
        name: 'Charger', 
        img: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        stock: 123,
        status: "active",
        price: "32 450 XAF",
    },
    { 
        id: 7, 
        name: 'Airpods', 
        img: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        stock: 123,
        status: "active",
        price: "32 450 XAF",
    },
    { 
        id: 8, 
        name: 'HP computer', 
        img: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        stock: 123,
        status: "active",
        price: "32 450 XAF",
    },
    { 
        id: 9, 
        name: 'Potato', 
        img: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        stock: 123,
        status: "active",
        price: "32 450 XAF",
    },
    { 
        id: 10, 
        name: 'Cassava', 
        img: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        stock: 123,
        status: "active",
        price: "32 450 XAF",
    },
    { 
        id: 11, 
        name: 'Mango fruit', 
        img: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        stock: 123,
        status: "active",
        price: "32 450 XAF",
    },
    { 
        id: 12, 
        name: 'Water bottle', 
        img: "https://images.pexels.com/photos/17748758/pexels-photo-17748758/free-photo-of-bois-lumineux-soleil-couchant-rue.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
        stock: 123,
        status: "active",
        price: "32 450 XAF",
    },
]